### ISSUE TITLE
Unicode characters cause the script to fail

### ISSUE THREAD

**Issue by KidaJiwo** [wolfborg/anitransfer#1]
When exporting my list, it reached the anime called "[Yuru Yuri ♪♪](https://www.anime-planet.com/anime/yuru-yuri-2)", and after wrongly identifying it as just "Yuru Yuri", manually selecting [the correct version](https://myanimelist.net/anime/12403/Yuru_Yuri♪♪) caused the script to crash. Manually selecting "None of these" will also crash the script. Only solution was editing the AnimePlanet json file and taking it out.

Traceback:
```Traceback (most recent call last):
  File "anitransfer.py", line 258, in <module>
    main()
  File "anitransfer.py", line 201, in main
    else: cache(i['name'], mal[0])
  File "anitransfer.py", line 49, in cache
    writer.writerow([name, malid])
  File "C:\Python\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 11-12: character maps to <undefined>```

**Comment by wolfborg** [comment]
Hey there, thanks for pointing this out! I think I'd had this issue at some point too but I thought I'd resolved it. Might've accidentally undone it before committing at some point. I'll look at applying the fix to this again and let you know when that's up.

**Comment by wolfborg** [comment]
The encoding fix should be up for this now. Let me know if this resolves the issue.

**Comment by wolfborg** [comment]
Oh, also for this fix some existing entries in the cache file had to be replaced, so if you pull the changes locally any additional mappings in your cache file might be gone unless you backed it up first. Would just mean you might have to reconfirm some titles again.

**Comment by KidaJiwo** [comment]
I did see the changes in the cache but I decided to run from a clean install just to make sure the issue was fixed for everyone. It managed to complete successfully, managing to save "Yuru Yuri San☆Hai!" and "Space☆Dandy" as well without any trouble. Thank you for the fix.

**Comment by wolfborg** [comment]
Awesome, glad to hear! If you'd like to send over your new cache file so I can incorporate the new mappings into the main one that would be great, but I'll go ahead and close this issue now anyways.
